### ISSUE TITLE
Sci2 Registration site returns error

### ISSUE THREAD

**Issue by spacevet** [CIShell/sci2#2]
Hello,

I would like to use Sci2 tool for my research project.
I went to Sci2 Registration page to create an account.

https://sci2.cns.iu.edu/user/registration.php

However, when I entered the information and pressed the Submit button, it returned an error "could not find driver".
Login page doesn't seem to be working either.
![Screen Shot 2021-02-13 at 12 01 43](https://user-images.githubusercontent.com/30957336/107840294-ec5e8f80-6df4-11eb-9ecc-c77313965b71.png)

Can somebody tell me how to download Sci2 tool?
Thank you in advance!

**Comment by bherr2** [comment]
The site is no longer being supported, but you can download the latest version of Sci2 here on GitHub: <https://github.com/CIShell/sci2/releases/tag/v1.3.0>
