### ISSUE TITLE
Unable to run in Ubuntu 20.04

### ISSUE THREAD

**Issue by simucentral** [CIShell/sci2#3]
Hi Team,
I am unable to run this in Ubuntu 20.04.
I have attached the log file here. 
Any help on this is much appreciated.
Thank You.
[1658906006151.log](https://github.com/CIShell/sci2/files/9195999/1658906006151.log)

**Comment by bherr2** [comment]
Which version of Java are you running? This only runs on Java 8. If you can't run Java 8, then we recommend using Sc2 via Docker instead. Instructions are here: https://github.com/CIShell/sci2-docker-vnc

**Comment by simucentral** [comment]
Thank You So Much. 
I managed to install and configure Java 8. Now, it is running.
Best Regards.
